### ISSUE TITLE
train_cuhk_word2_1_pool.m requires rgbMean value and dimension mis-match in subset features

### ISSUE THREAD

**Issue by BelaChakraborty** [layumi/Image-Text-Embedding#11]
Hello
I was trying to execute your code as I required it urgently: 

1) First there was an issue with a **dimension mis-match** of the **subset.features** required by line 275 in the file:**cukh_word2_pool.m** :
           net.params(first).value = reshape(single(subset.features'),1,1,7263,300);

As the subset.features produced by the **make_dictionary.m** in line 29 gives features of dimension 300x7264:
            subset.features = w_features(:,sub);
HOW CAN THIS BE SOLVED?

Also, You have commented line 273 and 274 line in the file cukh_word2_pool.m, should they be uncommented?:
%m = mean(subset.features,2);
%subset.features = subset.features-repmat(m,1,20074);

2) Next, when I try to run the training file train_cuhk_word2_1_pool.m, I get an error as: 
             Reference to non-existent field '**rgbMean**'.
        Error in train_cuhk_word2_1_pool (line 16)
             im_mean = imdb.rgbMean;

In the **prepare_imdb.m**, you have commented line 24 and 25 which has this variable, should these be uncommented?:
           %resize_image; % resize image to 256x256, return mm.
           %imdb.rgbMean = mm;

**Comment by BelaChakraborty** [comment]
I managed to figure this out...

I might contact with a different issue encountered

**Comment by Lkn1995** [comment]
hello, have you solve it .I have meet the same problem.
Reference to non-existent field 'rgbMean'.
Error in train_cuhk_word2_1_pool (line 16);
how did you solve it, thanks!
