### ISSUE TITLE
Error in train_cuhk_word2_1_pool (line 16);'rgbMean'.

### ISSUE THREAD

**Issue by Lkn1995** [layumi/Image-Text-Embedding#12]
hello, I have meet the problem when I run train_cuhk_word2_1_pool.m
**Reference to non-existent field 'rgbMean'.**
Error in train_cuhk_word2_1_pool (line 16); how to solve it , thanks!

**Comment by layumi** [comment]
HI @Lkn1995 
It should be the image dataset 3-channel mean. For example, [0.5,0.5,0.5].

I forget the details. One easy way is to directly use the rgbmean in the ImageNet pretrained model.

**Comment by Lkn1995** [comment]
Thank you, then is there any function that can replace .rgbMean.Because I don't understand how to use the rgbmean in the ImageNet pretrained model.I have not used matlab before, a little unfamiliar。thank you very much

**Comment by layumi** [comment]
I just found the code. You may uncomment these two lines. https://github.com/layumi/Image-Text-Embedding/blob/541b403a9d01066d7ba7b3fba7864b1d64dbd069/dataset/CUHK-PEDES-prepare/prepare_imdb.m#L24-L25

**Comment by Lkn1995** [comment]
I uncomment these two lines, and then I met another error,
**The input argument must be a positive integer or [].**
I don't what's wrong  ,is there any method to solve it?

**Comment by Lkn1995** [comment]
thanks ,it works!
