### ISSUE TITLE
Are layers 'fc1' & 'fc1' illustrated in the paper?

### ISSUE THREAD

**Issue by prismformore** [layumi/Image-Text-Embedding#3]
Hi, I am interested in how these two layers influence the experiment result, because it seems that these two layers are not showed in the arXiv paper but in your matlab code.

Thank you!

**Comment by layumi** [comment]
Hi @prismformore ,
Thank you. You are right. We haven't illustrated it in the first version .  
But we have added it into our revised version (it will be uploaded to arXiv after accepted).
Thank you.
