### ISSUE TITLE
The loss of Image CNN of training stage2 on CUHK-PEDES dataset suddenly increases a lot

### ISSUE THREAD

**Issue by ConstantineTheGreat** [layumi/Image-Text-Embedding#7]
Hi layumi, I run the train_cuhk_Rankloss_shift.m after running the train_cuhk_word2_1_pool.m, but after about 40 epochs, I found the training result of Image CNN to be bad(as Fig.1). I didn't change any hyper parameters. I found that the layer parameters of the first few layers of Image CNN became NaN after about 40 epochs. Do you know why this happens?
![stage2](https://user-images.githubusercontent.com/41257444/42804420-92ffb25c-89db-11e8-9d97-9983befd5c83.jpg)
Before that, the training result looked good when running the train_cuhk_word2_1_pool.m for training stage1(as Fig.2).
![stage1](https://user-images.githubusercontent.com/41257444/42805371-3b8f2950-89de-11e8-9cba-5a0b9743c7a9.jpg)

**Comment by layumi** [comment]
@ConstantineTheGreat 
Could you try to train it again?  
It may cause by some internal problem of Matconvnet by accident.

**Comment by ConstantineTheGreat** [comment]
I will try again. Thanks for your response!
